_geognn_encoder_hparams:
  dropout_rate: 0.1
  embed_dim: 256
  num_of_layers: 3
_logged_hparams:
  batch_size: 16
  dataset_size: 0
  notes: QM9
dropout_rate: 0.1
lr: 0.0001
mlp_hidden_size: 1024
num_of_mlp_layers: 3
out_size: 2
task_type: regression
